language: python
python: 
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7" 
env:
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py27
install:
  - pip install tox 
script:
  - tox -e $TOX_ENV
